CREATE TABLE dbo.Pr_GKO (
	GKOId INT IDENTITY (-199, 1)
   ,GKOName VARCHAR(100) NOT NULL
   ,GKOAddress VARCHAR(200) NOT NULL
   ,GKOEmail VARCHAR(50) NOT NULL
   ,GKOPhone VARCHAR(50) NULL
   ,GKOPhoneMobile VARCHAR(50) NULL
   ,CreaterId INT NOT NULL
   ,CreateDt SMALLDATETIME NOT NULL
   ,UpdaterId INT NOT NULL
   ,UpdateDt SMALLDATETIME NOT NULL
   ,CONSTRAINT PK_Pr_GKO PRIMARY KEY CLUSTERED (GKOId)
) ON [PRIMARY]
GO

CREATE UNIQUE INDEX IX_Pr_GKO
ON dbo.Pr_GKO (GKOName)
ON [PRIMARY]
GO