CREATE TABLE dbo.Pr_CityParts (
	Id INT IDENTITY (-199, 1)
   ,Name VARCHAR(50) NOT NULL
   ,CreaterId INT NOT NULL
   ,CreateDt SMALLDATETIME NOT NULL
   ,UpdaterId INT NOT NULL
   ,UpdateDt SMALLDATETIME NOT NULL
   ,CONSTRAINT PK_Pr_CityParts_Id PRIMARY KEY NONCLUSTERED (Id)
) ON [PRIMARY]
GO

CREATE UNIQUE INDEX UK_Pr_CityParts_Name
ON dbo.Pr_CityParts (Name)
ON [PRIMARY]
GO