CREATE TABLE dbo.Pr_GKH (
	GKHid INT IDENTITY (-1999, 1)
   ,GKHName VARCHAR(100) NOT NULL
   ,GKHAddress VARCHAR(200) NOT NULL
   ,GKHEmail VARCHAR(50) NOT NULL
   ,GKHPhone VARCHAR(50) NULL
   ,GKHPhoneMobile VARCHAR(50) NULL
   ,CreaterId INT NOT NULL
   ,CreateDt SMALLDATETIME NOT NULL
   ,UpdaterId INT NOT NULL
   ,UpdateDt SMALLDATETIME NOT NULL
   ,CONSTRAINT PK_Pr_GKH PRIMARY KEY CLUSTERED (GKHid)
) ON [PRIMARY]
GO

CREATE UNIQUE INDEX IDX_Pr_GKH_GKHName
ON dbo.Pr_GKH (GKHName)
ON [PRIMARY]
GO